[package]
name = "kaze_backend"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.24", features = ["derive"] }
axum = { version = "0.8.1", features = ["tokio", "macros", "multipart"] }
axum-server = "0.7.1"
http = "1.2.0"
tokio = { version = "1.43.0", features = ["rt-multi-thread", "signal"] }
tower-http = { version = "0.6.2", features = ["cors"] }
serde = { version = "1.0.217", features = ["derive"] }
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
aws-config = { version = "1.5.13", features = ["behavior-version-latest"] }
aws-sdk-secretsmanager = { version = "1.57.0" }
typst-pdf = { version = "0.12.0" }
serde_json = "1.0.135"
#uuid = { version = "1.11.0", features = ["v4"] }
