[package]
name = "kaze_backend"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.20", features = ["derive"] }
axum = { version = "0.8.0-alpha.1", features = ["tokio", "macros"] }
axum-server = "0.7.1"
http = "1.1.0"
tokio = { version = "1.41.1", features = ["rt-multi-thread", "signal"] }
tower-http = { version = "0.6.1", features = ["cors"] }
serde = { version = "1.0.214", features = ["derive"] }
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
aws-config = { version = "1.0.1", features = ["behavior-version-latest"] }
aws-sdk-secretsmanager = { version = "1.3.0" }
typst-pdf = { version = "0.12.0" }
serde_json = "1.0.135"
#uuid = { version = "1.11.0", features = ["v4"] }
