services:
  prometheus:
    image: prom/prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --web.enable-remote-write-receiver
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    healthcheck:
      test:  ["CMD", "wget", "-qO-", "http://localhost:9090/-/ready"]
      interval: 5s
      retries: 5
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      prometheus:
        condition: service_healthy
    ports:
      - "3000:3000"

  k6:
    image: grafana/k6
    volumes:
    - ./load_test.js:/scripts/load_test.js:ro
    environment:
      K6_OUT: experimental-prometheus-rw
      K6_PROMETHEUS_RW_SERVER_URL: http://prometheus:9090/api/v1/write
    command: run /scripts/load_test.js
